### ISSUE TITLE
Outlook uread count

### ISSUE THREAD

**Issue by rauldipeas** [streetturtle/rambox-extensions#8]
[This script](https://github.com/streetturtle/rambox-extensions/blob/master/outlook-unread-count.js) is outdated and no longer work anymore.

**Comment by AXeL-dev** [comment]
@rauldipeas still works for me, anyway, if you update your rambox to the latest version, i don't think that you'll need this script

**Comment by rauldipeas** [comment]
> @rauldipeas still works for me, anyway, if you update your rambox to the latest version, i don't think that you'll need this script

I'm runing latest version of Rambox, with or without the script, results are the same.

**Comment by AXeL-dev** [comment]
> > @rauldipeas still works for me, anyway, if you update your rambox to the latest version, i don't think that you'll need this script
> 
> I'm runing latest version of Rambox, with or without the script, results are the same.

Okay, try to get back to the old script then, check the following commit https://github.com/streetturtle/rambox-extensions/commit/2b7bf004f5eacca71161d9d9cc0b4bea1ee83dac

**Comment by rauldipeas** [comment]
All working again! Thanks!
![image](https://user-images.githubusercontent.com/12108031/60401525-10eef080-9b59-11e9-85a2-1ea49222d77a.png)
